-- MySQL Script generated by MySQL Workbench
-- Wed Sep 27 15:21:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chamados` DEFAULT CHARACTER SET utf8 ;
USE `chamados` ;

-- -----------------------------------------------------
-- Table `perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfil` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setor` (
  `id` INT NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `idperfil` INT NOT NULL,
  `idsetor` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_usuario_perfil_idx` (`idperfil` ASC) ,
  INDEX `fk_usuario_setor1_idx` (`idsetor` ASC) ,
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_setor1`
    FOREIGN KEY (`idsetor`)
    REFERENCES `setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chamado` (
  `id` INT NOT NULL,
  `descricao` TEXT NOT NULL,
  `status` INT NOT NULL,
  `data_abertura` BIGINT(10) NOT NULL,
  `data_atendimento` BIGINT(10) NULL,
  `data_cancelamento` BIGINT(10) NULL,
  `matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chamado_usuario1_idx` (`matricula` ASC) ,
  CONSTRAINT `fk_chamado_usuario1`
    FOREIGN KEY (`matricula`)
    REFERENCES `usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interacao` (
  `id` INT NOT NULL,
  `conteudo` TEXT NOT NULL,
  `data` BIGINT(10) NOT NULL,
  `idchamado` INT NOT NULL,
  `matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interacao_chamado1_idx` (`idchamado` ASC) ,
  INDEX `fk_interacao_usuario1_idx` (`matricula` ASC) ,
  CONSTRAINT `fk_interacao_chamado1`
    FOREIGN KEY (`idchamado`)
    REFERENCES `chamado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interacao_usuario1`
    FOREIGN KEY (`matricula`)
    REFERENCES `usuario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
